server:
  port: 8080

spring:
  application:
    name: beer-catalog-service

security:
  oauth2:
    client:
      client-id: {client-id}
      client-secret: {client-secret}
      access-token-uri: https://{okta-domain}/oauth2/default/v1/token
      user-authorization-uri: https://{okta-domain}/oauth2/default/v1/authorize
      scope:
        - openid
        - profile
        - email
    resource:
      user-info-uri: https://{okta-domain}/oauth2/default/v1/userinfo
      token-info-uri: https://{okta-domain}/oauth2/default/v1/introspect
      prefer-token-info: false