server:
  port: 8081

feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true

spring:
  application:
    name: edge-service

zuul:
  routes:
    home:
      path: /home
      url: http://localhost:8080

    beer-catalog-service:
      path: /beers
      url: http://localhost:8080

  sensitive-headers: Cookie,Set-Cookie

security:
  oauth2:
    client:
      client-id: {client-id}
      client-secret: {client-secret}
      access-token-uri: https://{okta-domain}/oauth2/default/v1/token
      user-authorization-uri: https://{okta-domain}/oauth2/default/v1/authorize
      scope:
      - openid
      - profile
      - email
    resource:
      user-info-uri: https://{okta-domain}/oauth2/default/v1/userinfo
      token-info-uri: https://{okta-domain}/oauth2/default/v1/introspect
      prefer-token-info: false